use anyhow::{Context, Result};
use serde::Deserialize;
use std::io::{BufRead, BufReader, Write};
use std::net::{TcpListener, TcpStream};
use std::path::Path;
use std::process::Command;

#[derive(Deserialize)]
struct OllamaResponse {
    response: String,
}

const PORT: u16 = 12345;

fn strip_fences(body: &str) -> &str {
    let lines: Vec<&str> = body.lines().collect();
    if lines.is_empty() || !lines[0].trim().starts_with("```") {
        return body;
    }
    let mut result = String::new();
    let mut in_fence = false;
    for line in lines {
        let t = line.trim();
        if t.starts_with("```") { in_fence = !in_fence; continue; }
        if in_fence {
            if t.starts_with("fn ") || t.starts_with("pub fn") || t == "}" { continue; }
            result.push_str(line);
            result.push('\n');
        }
    }
    let trimmed = result.trim().trim_end_matches('}').trim();
    if trimmed.is_empty() { body } else { Box::leak(trimmed.to_string().into_boxed_str()) }
}

fn call_llm(prompt: &str) -> Result<String> {
    let body = serde_json::json!({
        "model": "qwen2.5-coder:1.5b",
        "prompt": format!(
            "{}", prompt
        ),
        "stream": false,
        "options": { "temperature": 0.2 }
    });

    let client = reqwest::blocking::Client::builder()
        .timeout(std::time::Duration::from_secs(120))
        .build()?;

    let resp = client
        .post("http://localhost:11434/api/generate")
        .json(&body)
        .send()
        .context("Failed to connect to Ollama. Is it running?")?;

    if !resp.status().is_success() {
        anyhow::bail!("Ollama returned status: {}", resp.status());
    }

    Ok(resp.json::<OllamaResponse>()?.response)
}

fn generate_and_build(prompt: &str) -> Result<String> {
    let system = concat!(
        "You generate Rust function BODY for Karnelos OS kernel (bare-metal x86-64, no_std).\n",
        "Available: io::serial_write(b\"...\\r\\n\"), io::console_write(b\"...\\r\\n\"), io::serial_putc(c), io::console_putc(c)\n",
        "RULES:\n",
        "- Output ONLY the function body statements, one per line\n",
        "- No markdown, no code fences, no fn declaration, no closing brace\n",
        "- Use byte string literals: b\"...\"\n",
        "- End lines with \\r\\n in the string\n",
        "EXAMPLE for 'print hello': io::console_write(b\"Hello\\r\\n\");\n",
        "EXAMPLE for 'print counter': for i in 0..5 { io::console_write(b\"count: \"); io::console_putc(b'0' + i as u8); io::console_write(b\"\\r\\n\"); }\n"
    );

    let full_prompt = format!("{}\n\nRequest: {}", system, prompt);

    eprintln!("[daemon] Requesting LLM for: {}", prompt);

    match call_llm(&full_prompt) {
        Ok(response) => {
            let body = response.trim();
            let body = strip_fences(body);
            if body.len() < 3 {
                return Ok("ERROR: Response too short\n".to_string());
            }

            let code = format!(
                "// Auto-generated by Karnelos daemon.\n\
                 use crate::io;\n\n\
                 pub fn generated_main() {{\n\
                 {}\n\
                 }}\n",
                body
            );

            let daemon_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
            let kernel_src = daemon_dir.parent().unwrap().join("kernel/src/generated.rs");
            std::fs::write(&kernel_src, &code)
                .context("Failed to write generated.rs")?;
            eprintln!("[daemon] Code written to generated.rs");

            eprintln!("[daemon] Building kernel...");
            let home = std::env::var("HOME").unwrap_or_default();
            let path = format!("{}/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin", home);
            let status = Command::new("make")
                .args(["-C", "/Users/kartavyadikshit/Projects/Karnelos", "build"])
                .env_clear()
                .env("HOME", &home)
                .env("PATH", &path)
                .env("RUSTUP_HOME", format!("{}/.rustup", home))
                .env("CARGO_HOME", format!("{}/.cargo", home))
                .status()
                .context("Failed to run make build")?;

            if status.success() {
                eprintln!("[daemon] Build OK");
                Ok("BUILD_OK\n".to_string())
            } else {
                eprintln!("[daemon] Build FAILED");
                Ok("BUILD_FAILED\n".to_string())
            }
        }
        Err(e) => {
            eprintln!("[daemon] LLM error: {}", e);
            Ok(format!("ERROR: {}\n", e))
        }
    }
}

fn handle_connection(mut stream: TcpStream) -> Result<()> {
    let addr = stream.peer_addr()?;
    eprintln!("[daemon] Connection from {}", addr);

    let mut reader = BufReader::new(stream.try_clone()?);
    let mut line = String::new();

    while reader.read_line(&mut line)? > 0 {
        let trimmed = line.trim();
        eprintln!("[daemon] Received: {}", trimmed);

        if let Some(prompt) = trimmed.strip_prefix("KARNELOS_GEN:") {
            let result = generate_and_build(prompt)?;
            stream.write_all(result.as_bytes())?;
            stream.flush()?;
        }
        line.clear();
    }

    eprintln!("[daemon] Connection closed");
    Ok(())
}

fn main() -> Result<()> {
    eprintln!("[daemon] Karnelos daemon starting on port {}", PORT);
    let listener = TcpListener::bind(("127.0.0.1", PORT))
        .context("Failed to bind TCP listener")?;
    eprintln!("[daemon] Listening on 127.0.0.1:{}", PORT);

    for stream in listener.incoming() {
        match stream {
            Ok(stream) => {
                if let Err(e) = handle_connection(stream) {
                    eprintln!("[daemon] Connection handler error: {}", e);
                }
            }
            Err(e) => eprintln!("[daemon] Accept error: {}", e),
        }
    }

    Ok(())
}
