use anyhow::{Context, Result};
use serde::Deserialize;
use std::path::Path;
use std::process::Command;

#[derive(Deserialize)]
struct OllamaResponse {
    response: String,
}

fn call_llm(system: &str, prompt: &str) -> Result<String> {
    let body = serde_json::json!({
        "model": "qwen2.5-coder:1.5b",
        "prompt": format!("{}\n\nUser request: {}\n\nOutput ONLY the function body, no markdown, no code fences:", system, prompt),
        "stream": false,
        "options": { "temperature": 0.2, "num_predict": 512 }
    });

    let client = reqwest::blocking::Client::builder()
        .timeout(std::time::Duration::from_secs(120))
        .build()?;

    let resp = client
        .post("http://localhost:11434/api/generate")
        .json(&body)
        .send()
        .context("Failed to connect to Ollama. Is it running on localhost:11434?")?;

    if !resp.status().is_success() {
        anyhow::bail!("Ollama returned status: {}", resp.status());
    }

    Ok(resp.json::<OllamaResponse>()?.response)
}

fn sanitize_body(body: &str) -> String {
    let mut out = String::new();
    for line in body.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("```") || trimmed.starts_with("fn ") || trimmed.starts_with("pub fn") || trimmed == "}" {
            continue;
        }
        out.push_str(line);
        out.push('\n');
    }
    let trimmed = out.trim().trim_end_matches('}').trim();
    trimmed.to_string()
}

const TEMPLATE: &str = r#"// Auto-generated by Karnelos generator.
use crate::io;

pub fn generated_main() {
BODY_HERE
}
"#;

fn main() -> Result<()> {
    let args: Vec<String> = std::env::args().collect();
    if args.len() < 2 {
        eprintln!("Usage: karnelos-gen \"<description of what to generate>\"");
        std::process::exit(1);
    }
    let prompt = &args[1];

    let system = concat!(
        "You generate Rust function BODY for Karnelos OS kernel (bare-metal x86-64, no_std).\n",
        "Available: io::serial_write(b\"...\\r\\n\"), io::console_write(b\"...\\r\\n\"), io::serial_putc(c), io::console_putc(c)\n",
        "RULES:\n",
        "- Output ONLY the function body statements, one per line\n",
        "- No markdown, no code fences, no fn declaration, no closing brace\n",
        "- Use byte string literals: b\"...\"\n",
        "- End lines with \\r\\n in the string\n",
        "EXAMPLE for 'print hello': io::console_write(b\"Hello\\r\\n\");\n",
        "EXAMPLE for 'print counter': for i in 0..5 { io::console_write(b\"count: \"); io::console_putc(b'0' + i as u8); io::console_write(b\"\\r\\n\"); }\n"
    );

    println!("[generator] Requesting code from LLM...");

    match call_llm(system, prompt) {
        Ok(response) => {
            let body = sanitize_body(&response);
            if body.len() < 5 {
                println!("[generator] LLM response too short. Raw response:\n{}", response);
                return Ok(());
            }

            let code = TEMPLATE.replace("BODY_HERE", &body);
            let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
            let kernel_src = manifest_dir.parent().unwrap().join("kernel/src/generated.rs");
            std::fs::write(&kernel_src, &code)
                .context("Failed to write generated.rs")?;
            println!("[generator] Code written to {}", kernel_src.display());
            println!("[generator] Generated code:\n{}", body);

            println!("[generator] Building kernel...");
            let home = std::env::var("HOME").unwrap_or_default();
            let path = format!("{}/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin", home);
            let status = Command::new("make")
                .args(["-C", "/Users/kartavyadikshit/Projects/Karnelos", "build"])
                .env_clear()
                .env("HOME", &home)
                .env("PATH", &path)
                .env("RUSTUP_HOME", format!("{}/.rustup", home))
                .env("CARGO_HOME", format!("{}/.cargo", home))
                .env("BOOTLOADER_FEATURES", "map_physical_memory")
                .status()
                .context("Failed to run make build")?;
            if status.success() {
                println!("[generator] Build OK! Run: make run");
            } else {
                eprintln!("[generator] Build FAILED");
            }
        }
        Err(e) => {
            eprintln!("[generator] Error: {}", e);
        }
    }
    Ok(())
}
